### ISSUE TITLE
Reserved words for implicit declaration and resolution

### ISSUE THREAD

**Issue by diesalbla** [arrow-kt/kotlin#1]
The goal of this issue is to add to the Kotlin language two reserved words, `give` and `given`, 

* Add the words to the definition of the language 
* Update the documentation to include the two reserved words
* Remove any use of these words in the Kotlin compiler and libraries. 
* Test: for each reserved word, add a Kotlin code snippet in which the word is used as a variable name.

**Comment by raulraja** [comment]
This has changed to `extension` as denotation that the interface or type is a family of extensions or static functions and `with` instead of `given`. `with` is already a popular function in Kotlin that activates the context of a value as the `this` scope exposing all its methods as if it where in their scope. `with(account) { name.trim() }`
